django_tutorials/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(),  name='books'),
    path('books/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('authors/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path(r'borrowed/', views.LoanedBooksAllListView.as_view(), name='all-borrowed'),
    path('authors/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('authors/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('authors/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
]

django_tutorials/django_tutorials/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('journal.urls')),
    path('journal/', include(('journal.urls', 'journal'), namespace='journal')),
    path('catalog/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    path('accounts/', include('django.contrib.auth.urls')),
]

django_tutorials/catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date
import uuid

# Create your models here.


class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn_link = "https://www.isbn-international.org/content/what-isbn"
    isbn = models.CharField('ISBN', max_length=13,
                            help_text=f'13 Character <a href="{isbn_link}">ISBN number</a>')
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('catalog:book-detail', args=[str(self.id)])


class BookInstance(models.Model):
    """ Model representing a specific copy of a book (i.e. that can be borrowed from the library).
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        """ Meta data, in this case we instruct to order list views by due_back.

        """
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('catalog:author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

django_tutorials/catalog/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

##############################
### - test stuff:
##############################
#
# from .models import NoSugar
#
#
# class NoSugarForm(forms.ModelForm):
#     """ Simple Form to track No Sugar habit.
#         Do something quick and dirty.
#     """
#     class Meta:
#         model = NoSugar
#         fields = ('entry_date', 'completed', 'note',)

django_tutorials/catalog/views.py
import datetime
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.views import generic

from .models import Book, Author, BookInstance, Genre
from .forms import RenewBookForm


# Create your views here.

@login_required
def index(request):
    """ View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    # The 'all()' is implied by default.
    num_authors = Author.objects.count()
    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'catalog/index.html', context=context)


@method_decorator(login_required, name='dispatch')
class BookListView(generic.ListView):
    """ Create generic list view on the Book model."""
    model = Book
    paginate_by = 10
    # Simple way to override default data:
    context_object_name = 'my_book_list'    # your own name for the list as a template variable
    # queryset = Book.objects.filter(title__icontains='war')[:5]      # Get 5 books containing the title war
    template_name = 'books/book_list.html'    # Specify your own template name/location

    def get_queryset(self):
        """Another way to override the query set. This one is more flexible..."""
        return Book.objects.all()     # Get 5 books containing the title war.

    def get_context_data(self, **kwargs):
        """ We might also override get_context_data() in order to pass additional context variables to the template
            (e.g. the list of books is passed by default). The fragment below shows how to add a variable named
            "some_data" to the context (it would then be available as a template variable).

            When doing this it is important to follow the pattern used below:
            1) First get the existing context from our superclass.
            2) Then add your new context information.
            3) Then return the new (updated) context.
        """
        # Call the base implementation first to get the context
        context = super(BookListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['some_data'] = 'This is just some data'
        return context


@method_decorator(login_required, name='dispatch')
class BookDetailView(generic.DetailView):
    model = Book


@method_decorator(login_required, name='dispatch')
class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10
    context_object_name = 'my_author_list'
    template_name = 'authors/author_list.html'


@method_decorator(login_required, name='dispatch')
class AuthorDetailView(generic.DetailView):
    model = Author


class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    """
    Generic class-based view listing books on loan to current user.
    """
    model = BookInstance
    template_name ='catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        """ Query for books that are 'on loan' and are borrowed by User. Order by due back. """
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


class LoanedBooksAllListView(PermissionRequiredMixin,generic.ListView):
    """
    Generic class-based view listing all books on loan. Only visible to users with can_mark_returned permission.
    """
    model = BookInstance
    permission_required = 'catalog.can_mark_returned'
    template_name = 'catalog/bookinstance_list_borrowed_all.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')


@permission_required('catalog.can_mark_returned')
#@permission_required('catalog.can_edit')
def renew_book_librarian(request, pk):
    """
    View function for renewing a specific BookInstance by librarian
    """
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        book_renewal_form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if book_renewal_form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_instance.due_back = book_renewal_form.cleaned_data['renewal_date']
            book_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('catalog:all-borrowed'))

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        book_renewal_form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
    'form': book_renewal_form,
    'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)


# Generic views / forms that add/update/delete records. You can use for habits, exercises etc.

class AuthorCreate(CreateView):
    model = Author
    fields = '__all__'
    initial = {'date_of_death': '05/01/2018'}


class AuthorUpdate(UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']


class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')

django_tutorials/catalog/templates/catalog/author_confirm_delete.html
{% extends "catalog/base_generic.html" %}

{% block content %}

    <h1>Delete Author</h1>

<p>Are you sure you want to delete the author: <strong>{{ author }}</strong>?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
    </form>

{% endblock %}

django_tutorials/catalog/templates/catalog/author_detail.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Author:</h1>

    <p>{{ author.id }}</p>
    <p><strong>Last Name:</strong> {{ author.last_name }}</p> <!-- author detail link not yet defined -->
    <p><strong>First Name:</strong> {{ author.first_name }}</p> <!-- author detail link not yet defined -->
    <p><strong>Date of Birth:</strong> {{ author.date_of_birth }}</p> <!-- author detail link not yet defined -->
    <p><strong>Date of Death:</strong> {{ author.date_of_death }}</p> <!-- author detail link not yet defined -->
    <br/>
    <span>
        <a href="{% url 'catalog:author_update' pk=author.pk %}"><h6>Update</h6></a>
        <a href="{% url 'catalog:author_delete' pk=author.pk %}"><h6>Delete</h6></a>
    </span>


    <div style="margin-left:20px;margin-top:20px">
        <h4>Books</h4>

        {% for book in author.book_set.all %}
            <hr>
        <p><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></p>
        {% endfor %}
    </div>

{% endblock %}

django_tutorials/catalog/templates/catalog/author_form.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

django_tutorials/catalog/templates/catalog/author_list.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Author List</h1>
    {% if my_author_list %}
        <ul>
        {% for author in my_author_list %}
            <li>
                <a href="{{ author.get_absolute_url }}">
                    <b>{{ author.last_name }}, {{ author.first_name }}</b>
                </a> ({{ author.date_of_birth }} - {{ author.date_of_death }})
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>There are no books in the library.</p>
    {% endif %}

{% endblock %}

django_tutorials/catalog/templates/catalog/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    <link rel="stylesheet" type="text/css" href="{% static 'catalog/styles.css' %}">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
            <ul class="sidebar-nav">
                <li><a href="{% url 'catalog:index' %}">Home</a></li>
                <li><a href="{% url 'catalog:books' %}">All Books</a></li>
                <li><a href="{% url 'catalog:authors' %}">All Authors</a></li>
                {% if user.is_authenticated %}
                    <li>User: {{ user.get_username }}</li>
                    <li><a href="{% url 'catalog:my-borrowed' %}">My Borrowed</a></li>
                    <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
                {% endif %}
               {% if perms.catalog.can_mark_returned %}
                    <hr />
                    <li>Staff</li>
                    <li><a href="{% url 'catalog:all-borrowed' %}">All Borrowed</a></li>
                    <li><a href="{% url 'catalog:author_create' %}">Add Author</a></li>
                {% endif %}
            </ul>
            {% endblock %}
        </div>
        <div class="col-sm-10">
            {% block content %}
            {% endblock %}
            <hr/>
            {% block pagination %}      <!-- Block which sets up pagination -->
                {% if is_paginated %}       <!-- Checks if pagination exists on the page -->
                <span class="pagination">
                    <span><a href="{{ request.path }}?page=1"><em>|< first&nbsp&nbsp</em></a></span>
                    {% if page_obj.has_previous %}      <!-- If previous page exists, add link to previous page. -->
                        <span><a href="{{ request.path }}?page={{ page_obj.previous_page_number }}"><em><< previous&nbsp&nbsp</em></a></span>
                    {% endif %}
                    <span><em>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.&nbsp&nbsp</em></span>
                    {% if page_obj.has_next %}          <!-- If next page exists, add link to next page. -->
                        <span><a href="{{ request.path }}?page={{ page_obj.next_page_number }}"><em>next >>&nbsp&nbsp</em></a></span>
                    {% endif %}
                    <span><a href="{{ request.path }}?page={{ page_obj.paginator.num_pages }}"><em>last >|</em></a></span>

                </div>
                {% endif %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

django_tutorials/catalog/templates/catalog/book_detail.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Title: {{ book.title }}</h1>

    <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
    <p><strong>Summary:</strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <p><strong>Language:</strong> {{ book.language }}</p>
    <!-- The forloop.last ensures that it will add comma and keep going until the last genre for the book:-->
    <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

    <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}
    <p><strong>Due to be returned:</strong> {{copy.due_back}}</p>
    {% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
    </div>
{% endblock %}

django_tutorials/catalog/templates/catalog/book_list.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Book List</h1>
    {% if my_book_list %}
        <ul>
        {% for book in my_book_list %}
            <li>
            <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

django_tutorials/catalog/templates/catalog/book_renew_librarian.html
{% extends "catalog/base_generic.html" %}

{% block content %}

    <h1>Renew: {{ book_instance.book.title }}</h1>
    <p>Borrower: {{ book_instance.borrower }}</p>
    <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <input type="submit" value="Submit">
    </form>

{% endblock %}

django_tutorials/catalog/templates/catalog/bookinstance_list_borrowed_all.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>All Borrowed Books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'catalog:book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }}) {% if perms.catalog.can_mark_returned %}- {{ bookinst.borrower }}{% endif %} {% if perms.catalog.can_mark_returned %}- <a href="{% url 'catalog:renew-book-librarian' bookinst.id %}">Renew</a>  {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

django_tutorials/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
        <ul>

        {% for bookinst in bookinstance_list %}
            <li class="{% if bookinst.is_overdue %}text-danger{% endif %}" {% if bookinst.is_overdue %}style="background-color:red"{% endif %}>
                <a href="{% url 'catalog:book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
            </li>
        {% endfor %}
        </ul>

    {% else %}
        <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

django_tutorials/catalog/templates/catalog/index.html
{% extends "catalog/base_generic.html" %}

{% block title %}<title>Override: Local Library</title>{% endblock %}

{% block content %}
<h1>Local Library Home</h1>
<p>Welcome to LocalLibrary, a website developed by <em>Mozilla Developer Network</em>!</p>
<h2>Dynamic content</h2>
<p>The library has the following record counts:</p>
<ul>
<li><strong>Books:</strong> {{ num_books }}</li>
<li><strong>Copies:</strong> {{ num_instances }}</li>
<li><strong>Copies available:</strong> {{ num_instances_available }}</li>
<li><strong>Authors:</strong> {{ num_authors }}</li>
</ul>
<!-- Using sessions, the line below gets a counter of site visits: -->
<p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>
{% endblock %}